(sysconf) add the environment file sysconf-env

diff --git a/sysconf/bin/sysconf b/sysconf/bin/sysconf
--- a/sysconf/bin/sysconf
+++ b/sysconf/bin/sysconf
@@ -35,20 +35,23 @@ usage() { (sed -e "/^###/d" -e "/^##/!d" $0 && echo -e "\e[35m${0##*/}: \e[31m$@
 # the log file
 logFile="${HOME}/keep/${0##*/}";
 
-# configuration source files are hosted here (until the automounter is configured)
-installHost=$NFS_HOST;
+# environment configuration
 
-# configuration source directories ...
-installShare="/media/share/linux";
-installBin="${installShare}/${0##*/}/bin";
+if [[ ! -r /etc/sysconf-env ]]; then
+    error() { echo -e "\e[35m${0##*/}: \e[31m$@\e[0m"; }
+    error "/etc/sysconf-env missing";
+    exit 1;
+fi
+
+source /etc/sysconf-env;
 
 # ensure source files are accessible
 
 if [[ ! -e "${installBin}" ]]; then
-    if [[ ! -e ${installShare} ]]; then
-        sudo mkdir -p ${installShare} || exit 1;
+    if [[ ! -e "${installShare}" ]]; then
+        sudo mkdir -p "${installShare}" || exit 1;
     fi
-    sudo mount ${installHost}:/export/share/linux ${installShare} || exit 1;
+    sudo mount "${installHost}:${installShare/media/export}" "${installShare}" || exit 1;
 fi
 
 # ensure no confusion over which binaries we are using
@@ -59,23 +62,27 @@ PATH="${installBin}:/usr/bin:/bin";
 
 source sysconf-functions;
 
-# process the first flag (if any) and quit
+# process the first flag only (if any)
 
-while [[ -n "${1%%[!-]*}" ]]; do
+while [[ "${1:0:1}" == "-" ]]; do
     source sysconf-flags;
+    exit;
 done
 
-# do it
+# set trap so success and failure are both logged
 
 result="\e[31mFAILED\e[0m";
 trap 'printf "%-23s %-7s %-23s ${result}\n" "$(date +"%x %X")" ${step} >> ${logFile}' EXIT;
 
+# get sudo password entered before going any further
 
 if [[ "${1/./}" != "$1" ]]; then
     [[ ${1%.99} == "$1" ]] && sudo pwd > /dev/null;
 else
     [[ "${1,,}" != "$1" ]] && sudo pwd > /dev/null;
 fi
+
+# delegate to a section specific script
 
 case "$1" in
 
